<?php
// clear_cart.php: removes all products from the session cart
// and automatically redirects to the cart page. It is the
// destination of the "Empty cart" button. It follows the
// Post/Redirect/Get pattern: the result message is stored in
// the session and shown on the destination page.

// session_start(): opens the session before any output
session_start();

// unset(): removes a specific key from the $_SESSION array.
// Here it only deletes the cart; the rest of the session stays
// active. session_destroy() is not used because it would end
// the whole session.
unset($_SESSION['cart']);

// Automatic redirect: the browser requests the cart page.
// The empty cart is displayed by itself (the "is empty" notice
// is generated by cart.php), so no flash message is used.
header("Location: cart.php");

// exit: stops execution.
exit;